backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

resourceFields: &resourceFields
  - {label: "Key", name: "key", widget: "string"}
  - {label: "Locale", name: "locale", widget: "select", select: ["ja", "en"]}
  - {label: "Name", name: "name", widget: "string"}
  - {label: "Body", name: "body", widget: "markdown"}
  - {label: "Relation", name: "relation", widget: "relation", collection: "tags", searchFields: ["title"], valueField: "title"}
  - {label: "Publish Date", name: "date", widget: "datetime"}

collections:
  - name: "plants"
    label: "Plants"
    folder: "src/plants"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      [*resourceFields]
