backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "tags"
    label: "Tags"
    folder: "src/tags"
    create: true
    slug: "{{key}}.{{locale}}"
    identifier_field: "{{key}}.{{locale}}"
    fields:
      - {name: "key", widget: "string"}
      - {name: "locale", widget: "select", options: ["ja", "en"], default: "ja"}
      - {name: "title", widget: "string"}
      - {name: "body", widget: "markdown"}

  - name: "plants"
    label: "Plants"
    folder: "src/plants"
    create: true
    slug: "{{key}}.{{locale}}"
    identifier_field: "{{key}}.{{locale}}"
    fields:
      - {name: "key", widget: "string"}
      - {name: "locale", widget: "select", options: ["ja", "en"], default: "ja"}
      - {name: "title", widget: "string"}
      - {name: "body", widget: "markdown"}
      - {name: "relation", widget: "relation", collection: "tags", searchFields: ["title"], valueField: "title", multiple: true}
